workflows:
  ios-release-player:
    name: iOS Unsigned Release - Player
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.varplayerios.varplayer
        SCHEME: Runner
        CONFIGURATION: Release
        ARCHIVE_PATH: build/ios/archive/Runner.xcarchive

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: (Optional) Override Bundle ID
        script: |
          if [ -n "$BUNDLE_ID" ]; then
            echo "Using BUNDLE_ID=$BUNDLE_ID"
            plutil -replace CFBundleIdentifier -string "$BUNDLE_ID" ios/Runner/Info.plist || true
            /usr/libexec/PlistBuddy -c "Set :PRODUCT_BUNDLE_IDENTIFIER $BUNDLE_ID" ios/Runner.xcodeproj/project.pbxproj 2>/dev/null || true
          fi

      - name: Pod install
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Resolve FLUTTER_ROOT for Xcode scripts
        script: |
          # يخلي سكربت xcode_backend.sh يشتغل بدون ما يفشل
          FLUTTER_ROOT="$(flutter sdk-path)"
          echo "FLUTTER_ROOT=$FLUTTER_ROOT"
          echo "FLUTTER_ROOT=$FLUTTER_ROOT" >> $CM_ENV
          echo "VERBOSE_SCRIPT_LOGGING=YES" >> $CM_ENV

      - name: Xcode archive (NO codesign)
        script: |
          set -euo pipefail
          source $CM_ENV

          xcodebuild -version

          # أرشِف بدون توقيع – مهم تعطيل كل شيء يخص الكودساين
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            archive \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            OTHER_CODE_SIGN_FLAGS="--keychain /dev/null" \
            FLUTTER_ROOT="$FLUTTER_ROOT" \
            VERBOSE_SCRIPT_LOGGING=YES | xcpretty

          echo "✅ Archive created at: $ARCHIVE_PATH"

      - name: Extract Runner.app from archive
        script: |
          set -euo pipefail
          APP_SRC="$ARCHIVE_PATH/Products/Applications/Runner.app"
          APP_DST="build/ios/iphoneos/Runner.app"

          if [ ! -d "$APP_SRC" ]; then
            echo "❌ Runner.app not found at $APP_SRC"
            ls -lah "$ARCHIVE_PATH/Products/Applications" || true
            exit 1
          fi

          rm -rf "$APP_DST"
          mkdir -p "$(dirname "$APP_DST")"
          cp -R "$APP_SRC" "$APP_DST"
          echo "✅ Copied Runner.app to $APP_DST"

      - name: Create unsigned IPA
        script: |
          set -euo pipefail
          rm -rf Payload build/ios/ipa
          mkdir -p Payload build/ios/ipa
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          IPA_NAME="VarPlayer-unsigned-${CM_BUILD_ID}.ipa"
          zip -qry "build/ios/ipa/$IPA_NAME" Payload
          echo "✅ Unsigned IPA: build/ios/ipa/$IPA_NAME"

      - name: Sanity print artifacts
        script: |
          echo "==> build/ios/iphoneos:"
          ls -lah build/ios/iphoneos || true
          echo "==> build/ios/ipa:"
          ls -lah build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa            # IPA غير موقّع (لـ Sideloadly)
      - build/ios/iphoneos/Runner.app  # تطبيق Runner.app جاهز

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
