workflows:
  ios-release-player:
    name: iOS Release Build - Player
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS IPA
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
