workflows:
  ios-release-player:
    name: iOS Unsigned Release - Player
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.varplayerios.varplayer
        SCHEME: Runner
        CONFIGURATION: Release
        ARCHIVE_PATH: build/ios/archive/Runner.xcarchive

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Flutter clean & pub get
        script: |
          set -euxo pipefail
          flutter clean
          flutter pub get

      - name: (Optional) Override Bundle ID
        script: |
          set -euxo pipefail
          if [ -n "$BUNDLE_ID" ]; then
            echo "Using BUNDLE_ID=$BUNDLE_ID"
            plutil -replace CFBundleIdentifier -string "$BUNDLE_ID" ios/Runner/Info.plist || true
            /usr/libexec/PlistBuddy -c "Set :PRODUCT_BUNDLE_IDENTIFIER $BUNDLE_ID" ios/Runner.xcodeproj/project.pbxproj 2>/dev/null || true
          fi

      - name: Pod install
        script: |
          set -euxo pipefail
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Resolve FLUTTER_ROOT for Xcode Run Script
        script: |
          set -euxo pipefail
          FLUTTER_ROOT="$(flutter sdk-path)"
          echo "FLUTTER_ROOT=$FLUTTER_ROOT"
          # نمرّر المتغير لخطوات لاحقة
          echo "FLUTTER_ROOT=$FLUTTER_ROOT" >> $CM_ENV
          echo "VERBOSE_SCRIPT_LOGGING=YES" >> $CM_ENV

      - name: Xcode archive (NO codesign, full logs)
        script: |
          set -euxo pipefail
          source $CM_ENV

          xcodebuild -version
          xcodebuild -workspace ios/Runner.xcworkspace -scheme "$SCHEME" -showBuildSettings | head -n 50 || true

          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            archive \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            OTHER_CODE_SIGN_FLAGS="--keychain /dev/null" \
            FLUTTER_ROOT="$FLUTTER_ROOT" \
            VERBOSE_SCRIPT_LOGGING=YES

      - name: Fallback - flutter build ios --no-codesign (if archive failed)
        script: |
          set -euxo pipefail
          if [ ! -d "$ARCHIVE_PATH/Products/Applications/Runner.app" ]; then
            echo "Archive not found; trying flutter build ios --no-codesign as fallback…"
            if ! flutter build ios --release --no-codesign; then
              echo "flutter build ios returned non-zero (expected sometimes when signing is disabled)."
            fi
            if [ ! -d "build/ios/iphoneos/Runner.app" ]; then
              echo "❌ Runner.app not produced by fallback."
              exit 1
            fi
          fi

      - name: Stage Runner.app
        script: |
          set -euxo pipefail
          if [ -d "$ARCHIVE_PATH/Products/Applications/Runner.app" ]; then
            mkdir -p build/ios/iphoneos
            rm -rf build/ios/iphoneos/Runner.app
            cp -R "$ARCHIVE_PATH/Products/Applications/Runner.app" build/ios/iphoneos/Runner.app
            echo "✅ Copied Runner.app from archive."
          else
            echo "✅ Using Runner.app from flutter build output."
          fi

      - name: Create unsigned IPA
        script: |
          set -euxo pipefail
          rm -rf Payload build/ios/ipa
          mkdir -p Payload build/ios/ipa
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          IPA_NAME="VarPlayer-unsigned-${CM_BUILD_ID}.ipa"
          (cd Payload && zip -qry "../build/ios/ipa/$IPA_NAME" .)
          echo "✅ Unsigned IPA: build/ios/ipa/$IPA_NAME"

      - name: Sanity print artifacts
        script: |
          set -euxo pipefail
          echo "==> build/ios/iphoneos:"
          ls -lah build/ios/iphoneos || true
          echo "==> build/ios/ipa:"
          ls -lah build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa            # IPA غير موقّع (لسيدلودلي)
      - build/ios/iphoneos/Runner.app  # Runner.app

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
