workflows:
  ios_ipa_min:
    name: iOS IPA (Sideloadly)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default

    # اربط ملفات التوقيع من UI > Code signing بهذين الاسمين
    code_signing:
      certificates:
        - ios_cert.p12
      provisioning_profiles:
        - Runner.mobileprovision

    scripts:
      - name: Get packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Flutter build (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Apply signing profiles
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          # اختر طريقة التصدير: development أو ad-hoc
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-path "$CM_BUILD_DIR/build/ios_archive.xcarchive" \
            --export-method development

    artifacts:
      - build/ios/ipa/*.ipa
