name: var_player
description: "VAR Player - مشغل خارجي للقنوات"
publish_to: 'none'
version: 1.0.0+1
wakelock_plus: ^1..0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  http: ^1.2.2
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo_1024.png
    - assets/icon_bg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_1024.png"
  adaptive_icon_foreground: "assets/logo_1024.png"
  adaptive_icon_background: "assets/icon_bg.png"
  remove_alpha_ios: true
